In [2]:
import torch
print(torch.__version__)

2.10.0+cu128


In [3]:
if torch.cuda.is_available():
    print('GPU is available')
    print(f"using GPU : {torch.cuda.get_device_name(0)}")
else:
    print('GPU not available')
    

GPU is available
using GPU : Tesla T4


# creating tensors

In [28]:
# using empty
a = torch.empty(2,3)
a

tensor([[-1.1436e-06,  4.4055e-41,  8.7032e-24],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [29]:
# check type
type(a)

torch.Tensor

In [30]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [31]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
# using rand
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [33]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [34]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [35]:
# other ways

# arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [36]:
# using linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [37]:
# using eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [38]:
# using full
torch.full((3,2),5)

tensor([[5, 5],
        [5, 5],
        [5, 5]])

# tensor shapes

In [70]:
X = torch.tensor([[1,2,3],[4,5,6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [71]:
X.shape

torch.Size([2, 3])

In [72]:
X2 = torch.empty_like(X)
X2

tensor([[        0, 385058976,         0],
        [        0,         1,         6]])

In [73]:
torch.zeros_like(X)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [74]:
torch.ones_like(X)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [75]:
# torch.rand_like(X)    -->  error
# rand generate floats not integers as in X


# datatypes

In [76]:
X.dtype

torch.int64

In [77]:
X3 = torch.tensor([1.0,2.0,3.0])
X3

tensor([1., 2., 3.])

In [78]:
X3.dtype

torch.float32

In [79]:
X4 = torch.tensor([1.0,2.0,3.0] , dtype=torch.int32)
X4

tensor([1, 2, 3], dtype=torch.int32)

In [80]:
X4.dtype

torch.int32

In [81]:
X5 = torch.tensor([[1,2,3],[4,5,6]] , dtype=torch.float32)
X5

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [82]:
torch.rand_like(X5) 

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [83]:
X.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [84]:
torch.rand_like(X , dtype=torch.float32) 

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])

# mathematical operations

In [85]:
x = torch.rand(2,2)
x

tensor([[0.9535, 0.7064],
        [0.1629, 0.8902]])

In [86]:
x+2

tensor([[2.9535, 2.7064],
        [2.1629, 2.8902]])

In [87]:
x-2

tensor([[-1.0465, -1.2936],
        [-1.8371, -1.1098]])

In [88]:
x*2

tensor([[1.9071, 1.4128],
        [0.3258, 1.7804]])

In [89]:
x/2

tensor([[0.4768, 0.3532],
        [0.0814, 0.4451]])

In [90]:
(x*100)//3

tensor([[31., 23.],
        [ 5., 29.]])

In [91]:
((x*100)//3)%2


tensor([[1., 1.],
        [1., 1.]])

In [92]:
x**2

tensor([[0.9092, 0.4990],
        [0.0265, 0.7925]])

In [93]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [94]:
a

tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [95]:
b

tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])

In [96]:
a+b

tensor([[0.5609, 0.5482, 1.5527],
        [0.9419, 0.7632, 1.2539]])

In [97]:
a-b

tensor([[ 0.4716, -0.4765, -0.2574],
        [-0.2558, -0.1268, -0.2017]])

In [98]:
a*b

tensor([[0.0231, 0.0184, 0.5862],
        [0.2054, 0.1416, 0.3829]])

In [99]:
a/b

tensor([[11.5604,  0.0700,  0.7156],
        [ 0.5728,  0.7151,  0.7228]])

In [100]:
a**b

tensor([[0.9709, 0.1818, 0.6749],
        [0.5269, 0.6008, 0.6266]])

In [101]:
a%b

tensor([[0.0250, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])

In [103]:
a*100//b

tensor([[1156.,    7.,   71.],
        [  57.,   71.,   72.]])

In [105]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [106]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [107]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [109]:
d = torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [110]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [111]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [112]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [113]:
torch.clamp(d, min=2 , max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# reduction operation

In [135]:
e = torch.randint(size=(2,3) , low=0, high=10 , dtype=torch.float32)
e

tensor([[7., 2., 3.],
        [8., 5., 6.]])

In [136]:
torch.sum(e)

tensor(31.)

In [137]:
torch.sum(e, dim=0)

tensor([15.,  7.,  9.])

In [138]:
torch.sum(e, dim=1)

tensor([12., 19.])

In [139]:
torch.mean(e)

tensor(5.1667)

In [140]:
torch.mean(e, dim=1)

tensor([4.0000, 6.3333])

In [141]:
torch.median(e)

tensor(5.)

In [142]:
torch.max(e)

tensor(8.)

In [143]:
torch.min(e)

tensor(2.)

In [144]:
torch.prod(e)

tensor(10080.)

In [145]:
torch.std(e)

tensor(2.3166)

In [146]:
torch.var(e)

tensor(5.3667)

In [147]:
torch.argmax(e)

tensor(3)

In [148]:
torch.argmin(e)

tensor(1)

# matrix operations

In [152]:
f = torch.randint(size=(2,3) , low=0, high=10 )
g = torch.randint(size=(3,2) , low=0, high=10 )

In [153]:
f

tensor([[1, 1, 2],
        [4, 7, 2]])

In [154]:
g

tensor([[5, 6],
        [1, 4],
        [5, 6]])

In [155]:
# matric multiplication
torch.matmul(f,g)

tensor([[16, 22],
        [37, 64]])

In [156]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [157]:
torch.dot(vector1,vector2)

tensor(11)

In [158]:
f

tensor([[1, 1, 2],
        [4, 7, 2]])

In [160]:
torch.transpose(f, 0,1)

tensor([[1, 4],
        [1, 7],
        [2, 2]])

In [163]:
h = torch.randint(size=(3,3) , low=0, high=10 , dtype=torch.float32)
h


tensor([[1., 2., 7.],
        [9., 2., 4.],
        [6., 6., 8.]])

In [164]:
torch.det(h)

tensor(190.0000)

In [165]:
torch.inverse(h)

tensor([[-0.0421,  0.1368, -0.0316],
        [-0.2526, -0.1789,  0.3105],
        [ 0.2211,  0.0316, -0.0842]])

# comparison operations

In [173]:
i = torch.randint(size=(2,3) , low=0, high=10 )
j = torch.randint(size=(2,3) , low=0, high=10 )

In [174]:
i

tensor([[5, 3, 6],
        [7, 8, 1]])

In [175]:
j

tensor([[2, 3, 2],
        [7, 9, 3]])

In [176]:
# greater than
i>j

tensor([[ True, False,  True],
        [False, False, False]])

In [177]:
i<j

tensor([[False, False, False],
        [False,  True,  True]])

In [178]:
i==j

tensor([[False,  True, False],
        [ True, False, False]])

In [179]:
i!=j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [180]:
i<=j

tensor([[False,  True, False],
        [ True,  True,  True]])

# special fuctions

In [186]:
k = torch.randint(size=(2,3) , low=0, high=10, dtype=torch.float32)
k

tensor([[2., 4., 8.],
        [9., 6., 1.]])

In [187]:
torch.log(k)

tensor([[0.6931, 1.3863, 2.0794],
        [2.1972, 1.7918, 0.0000]])

In [188]:
torch.exp(k)

tensor([[7.3891e+00, 5.4598e+01, 2.9810e+03],
        [8.1031e+03, 4.0343e+02, 2.7183e+00]])

In [189]:
torch.sqrt(k)

tensor([[1.4142, 2.0000, 2.8284],
        [3.0000, 2.4495, 1.0000]])

In [190]:
torch.sigmoid(k)

tensor([[0.8808, 0.9820, 0.9997],
        [0.9999, 0.9975, 0.7311]])

In [191]:
torch.softmax(k,dim=0)

tensor([[9.1105e-04, 1.1920e-01, 9.9909e-01],
        [9.9909e-01, 8.8080e-01, 9.1105e-04]])

In [192]:
torch.relu(k)

tensor([[2., 4., 8.],
        [9., 6., 1.]])

# inplace operations

In [193]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [194]:
m

tensor([[0.2028, 0.9792, 0.4947],
        [0.3617, 0.9687, 0.0359]])

In [195]:
n

tensor([[0.3041, 0.9867, 0.1290],
        [0.6887, 0.1637, 0.0899]])

In [197]:
m.add_(n)

tensor([[0.5069, 1.9659, 0.6237],
        [1.0504, 1.1323, 0.1258]])

In [198]:
m

tensor([[0.5069, 1.9659, 0.6237],
        [1.0504, 1.1323, 0.1258]])

In [199]:
n

tensor([[0.3041, 0.9867, 0.1290],
        [0.6887, 0.1637, 0.0899]])

In [200]:
torch.relu(m)

tensor([[0.5069, 1.9659, 0.6237],
        [1.0504, 1.1323, 0.1258]])

In [201]:
m.relu_()

tensor([[0.5069, 1.9659, 0.6237],
        [1.0504, 1.1323, 0.1258]])

In [202]:
m

tensor([[0.5069, 1.9659, 0.6237],
        [1.0504, 1.1323, 0.1258]])

# copying a tensor

In [203]:
a = torch.rand(2,3)
a

tensor([[0.3139, 0.1219, 0.3516],
        [0.2316, 0.2847, 0.3520]])

In [204]:
b = a

In [205]:
b

tensor([[0.3139, 0.1219, 0.3516],
        [0.2316, 0.2847, 0.3520]])

In [206]:
a[0][0] = 0

In [207]:
a

tensor([[0.0000, 0.1219, 0.3516],
        [0.2316, 0.2847, 0.3520]])

In [208]:
b

tensor([[0.0000, 0.1219, 0.3516],
        [0.2316, 0.2847, 0.3520]])

In [209]:
id(a)


135026423627312

In [210]:
id(b)

135026423627312

In [211]:
c = a.clone()

In [212]:
a[1][1] = 4

In [213]:
a

tensor([[0.0000, 0.1219, 0.3516],
        [0.2316, 4.0000, 0.3520]])

In [214]:
c

tensor([[0.0000, 0.1219, 0.3516],
        [0.2316, 0.2847, 0.3520]])

In [215]:
id(a)

135026423627312

In [216]:
id(c)

135026421750336

# tensor operation on gpu

In [217]:
torch.cuda.is_available()

True

In [219]:
device = torch.device('cuda')
device

device(type='cuda')

In [220]:
# creating a tensor on gpu
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [221]:
# moving an existing tensor to gpu
a = torch.rand(2,3)
a

tensor([[0.2828, 0.2420, 0.4928],
        [0.5772, 0.3771, 0.2440]])

In [223]:
b = a.to(device)

In [224]:
b + 5

tensor([[5.2828, 5.2420, 5.4928],
        [5.5772, 5.3771, 5.2440]], device='cuda:0')

In [227]:
import time

size = 10000

matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

start_time = time.time()
cpu_result = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time

cpu_time

8.586233139038086

In [228]:
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time = time.time()
cpu_result = torch.matmul(matrix_gpu1,matrix_gpu2)
gpu_time = time.time() - start_time

gpu_time

0.27075791358947754

In [229]:
gain = 8.586233139038086/0.27075791358947754
gain

31.711845556826496

# reshaping tensors

In [230]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [231]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [232]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [234]:
b = torch.rand(2,3,4)
b

tensor([[[0.5448, 0.8393, 0.9212, 0.6474],
         [0.4833, 0.6609, 0.7179, 0.9443],
         [0.3657, 0.2163, 0.7112, 0.8602]],

        [[0.1207, 0.1966, 0.7261, 0.2219],
         [0.5751, 0.4702, 0.8808, 0.2473],
         [0.3847, 0.8570, 0.6584, 0.5999]]])

In [236]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [237]:
c = torch.rand(226,226,3)
c

tensor([[[0.5252, 0.6939, 0.8612],
         [0.9147, 0.5090, 0.4515],
         [0.1835, 0.2901, 0.4137],
         ...,
         [0.7082, 0.9614, 0.8600],
         [0.5598, 0.7877, 0.8234],
         [0.5292, 0.9189, 0.4228]],

        [[0.4618, 0.0404, 0.4499],
         [0.8578, 0.3893, 0.5785],
         [0.8004, 0.0154, 0.5066],
         ...,
         [0.3388, 0.1540, 0.2346],
         [0.5755, 0.0809, 0.5796],
         [0.2722, 0.5780, 0.2190]],

        [[0.5632, 0.6506, 0.9685],
         [0.4560, 0.8337, 0.1882],
         [0.4008, 0.5511, 0.5389],
         ...,
         [0.7393, 0.0539, 0.2757],
         [0.3008, 0.6329, 0.6563],
         [0.0864, 0.0676, 0.1060]],

        ...,

        [[0.7673, 0.2733, 0.4772],
         [0.2417, 0.1558, 0.4949],
         [0.8443, 0.4516, 0.6969],
         ...,
         [0.4646, 0.0353, 0.2315],
         [0.3161, 0.3135, 0.5755],
         [0.9209, 0.7319, 0.8867]],

        [[0.4487, 0.2998, 0.4749],
         [0.8833, 0.8950, 0.1046],
         [0.

In [241]:
# unsqueeze
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [243]:
d = torch.rand(1,20)
d

tensor([[0.8079, 0.7660, 0.0623, 0.2263, 0.2813, 0.3342, 0.9627, 0.1742, 0.3182,
         0.4952, 0.0557, 0.2057, 0.2101, 0.2422, 0.1398, 0.2367, 0.3263, 0.1190,
         0.5565, 0.4357]])

In [245]:
d.squeeze(0).shape

torch.Size([20])

# numpy and pytorch

In [246]:
import numpy as np

In [247]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [249]:
b = a.numpy()

In [250]:
type(b)

numpy.ndarray

In [252]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [253]:
d = torch.from_numpy(c)

In [254]:
type(d)

torch.Tensor